spring:
  application:
    name: NewsCheck
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

server:
  port: ${PORT:8080}

newscheck:
  collect:
    interval: ${COLLECT_INTERVAL:PT1H}

naver:
  api:
    client-id: ${NAVER_CLIENT_ID:}
    client-secret: ${NAVER_CLIENT_SECRET:}